//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKho.Databases.Entity_FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputInfo
    {
        public int Id { get; set; }
        public int IdInputInfo { get; set; }
        public int IdOutput { get; set; }
        public Nullable<double> OutputPrice { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> IdCustomer { get; set; }
        public string States { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual InputInfo InputInfo { get; set; }
        public virtual Output Output { get; set; }
    }
}
